version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:3000"
    environment:
      - PORT=3000
      - PG_USERNAME=postgres
      - PG_PASSWORD=mysecretpassword
      - PG_DATABASE=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULL_PREFIX=bull
    depends_on:
      - redis
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - $PWD/.volumes/redis/dir:/data
    ports:
      - "6379:6379"
